
stages:
  - test
  - deploy

test:cargo:
  image: rustdocker/rust:nightly
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo build --all --verbose
    - cargo build --examples --verbose
    - cargo test --verbose
  
pages:
  image: rustdocker/rust:nightly
  stage: deploy
  only:
    - master
  script:
    - cargo doc --no-deps
    - rm -rf public
    - mkdir public
    - cp -R target/doc/* public
  artifacts:
    paths:
      - public

deploy:crates:
  image: rustdocker/rust:nightly
  stage: deploy
  only:
    - pre-release
    - release
  when: manual
  script:
    - cargo login $CRATES_API_TOKEN
    - cargo package
    - cargo publish
