
stages:
  - test
  - doc
  - deploy

test:cargo:
  image: rustdocker/rust:nightly
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo build --all --verbose
    - cargo build --examples --verbose
    - cargo test --verbose
  
doc:cargo:
  image: rustdocker/rust:nightly
  stage: doc
  only:
    - master
  script:
    - cargo doc --no-deps
    - rm -rf public
    - mkdir public
    - cp -R target/doc/* public
  artifacts:
    paths:
      - public

deploy:docs:
  image: ruby:2.1
  stage: deploy
  only:
    - master
  script:
    - gem install jekyll
    - jekyll build -d public/
  artifacts:
    paths:
      - public


deploy:crates:
  image: rustdocker/rust:nightly
  stage: deploy
  only:
    - pre-release
    - release
  when: manual
  script:
    - echo "TODO deploy"
