image: "rust:latest"

stages:
  - setup
  - build
  - test

setup:nightly:
  stage: setup
  script:
    - rustup update nightly
    - rustup default nightly
    - rustc --version && cargo --version
  
build:cargo:
  stage: build
  script:
    - cargo build --all --verbose
    - cargo build --examples --verbose


test:cargo:
  stage: test
  script:
    - cargo test --all --verbose