image: "rust:latest"

before_script:
  - rustup update nightly
  - rustup default nightly
  - rustc --version && cargo --version
  
test:cargo:
  script:
    - cargo build --all --verbose
    - cargo build --examples --verbose
    - cargo test --all --verbose