language: rust
rust:
  - nightly

cache: cargo

script:
  - rustup default nightly-2018-04-11 # temporary hack to get it working
  - rustc --version
  - cargo --version
  - cargo build --all --verbose
  - cargo build --examples --verbose
  - cargo test --verbose
  - cargo doc --no-deps

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: target/doc/
  github_token: $GITHUB_TOKEN
  on:
    branch: master